from enum import Enum as _Enum
from enum import auto as _auto

class CatState(_Enum):
    Idle = 1,
    Walking = 2,
    Sprinting = 1,
    Resting = 1,

class CatDirection(_Enum):
    Left = _auto(),
    Right = _auto(),

class CatType(_Enum):
    Black = "black_000.png",
    Black_BlueEyes_PinkNose = "black_001.png",
    Black_YellowEyes = "black_002.png",
    Black_GreenEyes_PinkNose = "black_003.png",
    Blue_YellowEyes_PinkNose = "blue_000.png",
    Blue_YellowEyes = "blue_001.png",
    Blue = "blue_002.png",
    Blue_GreenEyes = "blue_003.png",
    Brown = "brown_000.png",
    Brown_GreenEyes_PinkNose = "brown_001.png",
    Brown_BlueEyes_PinkNose = "brown_002.png",
    Calico = "calico_000.png",
    Clown = "clown_000.png",
    Creme_BlueEyes = "creme_000.png",
    Creme_Light = "creme_001.png",
    Creme_Lighter = "creme_002.png",
    NeonDarkBlue = "dark_000.png",
    NeonDarkBlue_Bright = "dark_001.png",
    NeonDarkGreen = "dark_002.png",
    NeonDarkGreen_Bright = "dark_003.png",
    DarkBlue = "dark_004.png",
    Ghost = "ghost_000.png",
    Gold = "gold_000.png",
    Green = "green_000.png",
    Green_Lighter = "green_001.png",
    Grey = "grey_000.png",
    Grey_GreenEyes_RedNose = "grey_001.png",
    GreyBlack_BlueEyes_RedNose = "grey_002.png",
    Grey_Tabby_GreenEyes_RedNose = "grey_tabby_000.png",
    Grey_Tabby_RedNose = "grey_tabby_001.png",
    Grey_Tabby = "grey_tabby_002.png",
    Orange_GreenEyes_RedNose = "orange_002.png",
    OrangeBlack_GreenEyes = "orange_003.png",
    Orange_Tabby_GreenEyes_RedNose = "orange_tabby_000.png",
    Orange_Tabby_RedNose = "orange_tabby_001.png",
    Pink_BlueEyes_RedNose = "pink_000.png",
    Pink_RedEyes = "pink_001.png",
    Radioactive = "radioactive_000.png",
    Red = "red_000.png",
    SealPoint = "Seal_Point_000.png",
    SealPoint_Bright = "Seal_Point_001.png",
    White = "white_000.png",
    WhiteGrey = "white_grey_000.png",
    WhiteGrey_RedEyes = "white_grey_001.png",
    WhiteGrey_BlueEyes_RedNose = "white_grey_002.png",
